sonar.projectKey=rhel9-cis-ami
sonar.projectName=rhel9-cis-ami
sonar.projectVersion=0.1.0
sonar.organization=pw9876

# Sources — include HCL, YAML, and any Python helpers
sonar.sources=packer,ansible
sonar.exclusions=ansible/roles/**,ansible/collections/**

sonar.scm.provider=git
